apiVersion: v1
kind: Namespace
metadata:
  name: ingress-services

# ----------------------------------------------------------------------------
## ..:: BIG-IP CIS Secret for Management Username and Password ::..
## ----------------------------------------------------------------------------
##
## Please do a base64 of your BIG-IP username and password
##
## echo -n 'admin' | base64
## echo -n 'your-bigip-password-here' | base64
##
## ----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: bigip-login
  namespace: ingress-services
data:
  username: YWRtaW4=
  password: RGVmYXVsdDEyMzQh