## ----------------------------------------------------------------------------
## ..:: k3s-server installation ::..
## ----------------------------------------------------------------------------

- hosts: k3s-server
  remote_user: root
  tasks:

    - name: Set timezone to Europe/Rome
      timezone:
        name: Europe/Rome

    - name: Remove resolv.conf link
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Copy resolv.conf file on cluster's master and nodes
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf

    - name: Enable rc.local
      template:
        src: rc.local.j2
        dest: /etc/rc.local
        mode: 0700

    - name: setting hostname
      template:
        src: hostname.j2
        dest: /etc/hostname

    - name: Copy hosts file
      template:
        src: hosts.j2
        dest: /etc/hosts

    - name: Upgrade all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installing needed software
      apt:
        pkg:
        - nfs-client

    - name: Restart the server
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    ## ..:: Installing K3s ::..
    ## ------------------------------------------------------------------------

    - name: Installing -k3s-
      become: true
      become_user: ubuntu
      command: /bin/bash -c 'curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-cidr=10.243.0.0/16 --disable-network-policy --disable=traefik" sh -'
      args: 
         chdir: /home/ubuntu/

    - name: Creating .kube directory for ubuntu
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Creating config file for ubuntu to access k3s on infra
      become: true
      become_user: ubuntu
      command: /bin/bash -c "sudo cat /etc/rancher/k3s/k3s.yaml > ~/.kube/config"

    - name: create .kube directory for user ubuntu on infra-server (Ansible controller)
      local_action:
        module: file
        path: /home/ubuntu/.kube
        state: directory
        mode: 0755
        owner: ubuntu

    - name: copy .kube/config to user's kube config for user ubuntu on infra-server (Ansible controller)
      fetch:
        src: /home/ubuntu/.kube/config
        dest: /home/ubuntu/.kube/config
        flat: yes

    - name: Configure .kube/config on infra-server to access k3s-server
      local_action:
        module: lineinfile
        dest: /home/ubuntu/.kube/config
        regexp: '127.0.0.1' 
        line: '    server: https://{{ ansible_host }}:6443'
        backrefs: yes
