## ----------------------------------------------------------------------------
## ..:: k3s-server installation ::..
## ----------------------------------------------------------------------------

- hosts: k3s-server
  remote_user: root
  tasks:

    - name: Set timezone to Europe/Rome
      timezone:
        name: Europe/Rome

    - name: Remove resolv.conf link
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Copy resolv.conf file on cluster's master and nodes
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf

    - name: Enable rc.local
      template:
        src: rc.local.j2
        dest: /etc/rc.local
        mode: 0700

    - name: setting hostname
      template:
        src: hostname.j2
        dest: /etc/hostname

    - name: Copy hosts file
      template:
        src: hosts.j2
        dest: /etc/hosts

    - name: Upgrade all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installing needed software
      apt:
        pkg:
        - nfs-client
